import { useMemo } from "react";

import { type NextPage } from "next";
import Head from "next/head";

import { Parallax, ParallaxLayer } from "@react-spring/parallax";
import { useInView } from "@react-spring/web";

import ParticleText from "@/components/ParticleTexts";
import BouncingChevron from "@/components/BouncingChevron";
import RepeatedTitle from "@/components/RepeatedTitle";
import AboutMeContent from "@/components/AboutMeContent";
import LightDanceContent from "@/components/ProjectContents/LightDanceContent";
import SkillsContent from "@/components/SkillsContent";
import ScrollProgress from "@/components/ScrollProgress";

const TOTAL_SECTIONS = 3;

const Home: NextPage = () => {
  const [aboutMeRef, aboutMeInView] = useInView();
  const [lightDanceRef, lightDanceInView] = useInView();
  const [skillsRef, skillsInView] = useInView();

  const progress = useMemo(() => {
    if (aboutMeInView) {
      return 1 / TOTAL_SECTIONS;
    }
    if (lightDanceInView) {
      return 2 / TOTAL_SECTIONS;
    }
    if (skillsInView) {
      return 3 / TOTAL_SECTIONS;
    }
    return 0;
  }, [aboutMeInView, lightDanceInView, skillsInView]);

  return (
    <>
      <Head>
        <title>madmax</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ScrollProgress progress={progress} />
      <Parallax pages={11} className="top-0">
        {/* background */}
        <ParallaxLayer sticky={{ start: 0, end: 6 }} className="-z-40">
          <ParticleText text="madmax" />
          <div className="absolute top-3/4 grid w-full place-items-center">
            <BouncingChevron />
          </div>
        </ParallaxLayer>
        {/* about me */}
        <ParallaxLayer
          sticky={{ start: 1, end: 2.5 }}
          className="grid h-full w-full place-items-center"
        >
          <div
            className="top-1/5 relative -z-10 h-4/5 w-full bg-slate-400/20 backdrop-blur-xl"
            ref={aboutMeRef}
          ></div>
        </ParallaxLayer>
        <ParallaxLayer offset={1.3} speed={1.5}>
          <RepeatedTitle
            title="about"
            colorClasses={[
              "text-red-700",
              "text-red-800",
              "text-red-900",
              "text-red-900",
            ]}
            className="ml-36 mt-4"
          />
        </ParallaxLayer>
        <ParallaxLayer offset={1.3} speed={0.5}>
          <RepeatedTitle
            title="about"
            colorClasses={[
              "text-red-100",
              "text-red-200",
              "text-red-300",
              "text-red-600",
              "text-red-800",
            ]}
            className="ml-60 mt-12"
          />
        </ParallaxLayer>
        <ParallaxLayer
          sticky={{
            start: 1.3,
            end: 2,
          }}
        >
          <RepeatedTitle
            title="about"
            colorClasses={["text-red-100", "text-red-300", "text-red-600"]}
            className="ml-12"
          />
        </ParallaxLayer>
        <ParallaxLayer
          sticky={{ start: 1, end: 2.5 }}
          className="grid h-full w-full place-items-center"
        >
          <div className="top-1/5 relative -z-10 h-4/5 w-full">
            <AboutMeContent />
          </div>
        </ParallaxLayer>
        {/* projects */}
        {/* light dance */}
        <ParallaxLayer
          sticky={{ start: 4.5, end: 6 }}
          className="grid h-full w-full place-items-center"
        >
          <div
            className="top-1/5 relative -z-10 h-4/5 w-full bg-slate-400/20 backdrop-blur-xl"
            ref={lightDanceRef}
          ></div>
        </ParallaxLayer>
        <ParallaxLayer offset={4.8} speed={1.5}>
          <RepeatedTitle
            title="project"
            colorClasses={[
              "text-red-700",
              "text-red-800",
              "text-red-900",
              "text-red-900",
            ]}
            className="ml-12 mt-4"
          />
        </ParallaxLayer>
        <ParallaxLayer offset={4.8} speed={0.5}>
          <RepeatedTitle
            title="project"
            colorClasses={[
              "text-red-100",
              "text-red-200",
              "text-red-300",
              "text-red-600",
              "text-red-800",
            ]}
            className="ml-60 mt-12"
          />
        </ParallaxLayer>
        <ParallaxLayer
          sticky={{
            start: 4.8,
            end: 5.2,
          }}
        >
          <RepeatedTitle
            title="project"
            colorClasses={["text-red-100", "text-red-300", "text-red-600"]}
            className="ml-36"
          />
        </ParallaxLayer>
        <ParallaxLayer
          sticky={{ start: 4.5, end: 6 }}
          className="grid h-full w-full place-items-center"
        >
          <div className="top-1/5 relative h-4/5 w-full">
            <LightDanceContent />
          </div>
        </ParallaxLayer>
        {/* skills */}
        <ParallaxLayer offset={7} className="-z-40">
          <div className="h-full bg-gradient-to-b from-black to-[var(--mantine-color-dark-7)]"></div>
        </ParallaxLayer>
        <ParallaxLayer
          sticky={{
            start: 8.3,
            end: 10,
          }}
        >
          <div ref={skillsRef}></div>
          <SkillsContent />
        </ParallaxLayer>
      </Parallax>
    </>
  );
};

export default Home;
